"""Build the Safra Operator Console Windows installer.

Three steps:
  1. PyInstaller bundles the app into a standalone folder — a real
     SafraConsole.exe plus _internal/ (Python runtime, the ui/ tree, and
     pywebview so the app renders in an embedded WebView2 window), no Python
     install needed on the target machine.
  2. Inno Setup (ISCC) packs that into a per-user installer,
     dist/SafraConsole-Setup.exe: installs per-user under LocalAppData
     (no admin), Start-Menu shortcut, uninstaller, and — on an update — the
     Restart Manager closes the running app while [Run] relaunches it (the same
     path the app's one-click silent auto-update drives via /SILENT). It also
     chains the WebView2 Evergreen bootstrapper, run only when the runtime is
     missing, so the app works out of the box without depending on the browser.
  3. Writes dist/latest.json (the update feed: version, the installer's
     download URL, its sha256).

Requires pyinstaller + pywebview (pip) and Inno Setup 6 (ISCC.exe). Downloads
the WebView2 bootstrapper on first run (cached in build/).
Usage:  python tools/build_installer.py [--base-url URL] [--iscc PATH]
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS)
DIST = os.path.join(REPO, "dist")
BUILD = os.path.join(REPO, "build")
ICON = os.path.join(TOOLS, "SafraConsole.ico")

sys.path.insert(0, REPO)
from version import VERSION  # noqa: E402

SETUP_NAME = "SafraConsole-Setup.exe"
# The Evergreen bootstrapper (~2 MB). The installer runs it only when the target
# machine lacks the WebView2 runtime; it then downloads + installs the runtime,
# which Microsoft keeps security-patched. Cached in build/ across builds.
WV2_BOOTSTRAP_URL = "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
WV2_BOOTSTRAP = os.path.join(BUILD, "MicrosoftEdgeWebview2Setup.exe")
DEFAULT_BASE_URL = ("https://github.com/Safra-Robotics/safra-console"
                    "/releases/latest/download")
DEFAULT_ISCC = os.path.join(os.environ.get("LOCALAPPDATA", ""),
                            r"Programs\Inno Setup 6\ISCC.exe")

# real Inno syntax; only @TOKENS@ are substituted (avoids brace-escaping pain).
# AppId: {{GUID} renders to {GUID} at runtime — keep it fixed across releases
# so upgrades are recognized.
ISS = r"""; generated by tools/build_installer.py — do not edit by hand
[Setup]
AppId={{7C3F2A18-9D4B-4E6A-B1C2-3F4A5B6C7D8E}
AppName=Safra Operator Console
AppVersion=@VERSION@
AppPublisher=Safra Robotics
AppPublisherURL=https://safrarobotics.com
DefaultDirName={localappdata}\Programs\SafraConsole
DefaultGroupName=Safra Operator Console
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=@OUTDIR@
OutputBaseFilename=SafraConsole-Setup
SetupIconFile=@ICON@
UninstallDisplayIcon={app}\SafraConsole.exe
UninstallDisplayName=Safra Operator Console
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
; On an in-place update the Restart Manager CLOSES the running app so its files
; can be replaced; relaunch is handled explicitly by [Run] below (in both
; interactive and silent installs), so RestartApplications stays off to keep the
; silent auto-update relaunch deterministic — no RM restart racing the [Run].
CloseApplications=yes
RestartApplications=no

[Files]
Source: "@SRCDIR@\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; WebView2 Evergreen bootstrapper — extracted to {tmp} and run by InstallWebView2
; (below) only when the runtime is missing, then deleted.
Source: "@WV2SETUP@"; DestDir: "{tmp}"; Flags: deleteafterinstall; AfterInstall: InstallWebView2

[Icons]
Name: "{group}\Safra Operator Console"; Filename: "{app}\SafraConsole.exe"
Name: "{autodesktop}\Safra Operator Console"; Filename: "{app}\SafraConsole.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Run]
; interactive install: optional "Launch" checkbox on the finished page
Filename: "{app}\SafraConsole.exe"; Description: "Launch Safra Operator Console"; Flags: nowait postinstall skipifsilent
; silent auto-update: relaunch the app after an in-place update
; (WizardSilent is true only under /SILENT or /VERYSILENT)
Filename: "{app}\SafraConsole.exe"; Flags: nowait; Check: WizardSilent

[Code]
// Detect the WebView2 Evergreen runtime (per-machine or per-user). The runtime
// is registered by EdgeUpdate (a 32-bit app), so a 64-bit OS stores it under
// WOW6432Node. A valid install has a non-empty 'pv' other than 0.0.0.0.
function WebView2RuntimeInstalled(): Boolean;
var
  pv: String;
begin
  Result := False;
  if RegQueryStringValue(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', pv) then
    Result := (pv <> '') and (pv <> '0.0.0.0');
  if (not Result) and RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', pv) then
    Result := (pv <> '') and (pv <> '0.0.0.0');
  if (not Result) and RegQueryStringValue(HKCU, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', pv) then
    Result := (pv <> '') and (pv <> '0.0.0.0');
end;

// Runs after the bootstrapper is copied to {tmp}. Installs the runtime silently
// only when it is absent; a failure here is non-fatal (the app still ships a
// browser fallback), so we don't abort the install.
procedure InstallWebView2();
var
  ResultCode: Integer;
begin
  if not WebView2RuntimeInstalled() then
    Exec(ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe'), '/silent /install', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
end;
"""


def run(cmd, cwd=None):
    print("+", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=cwd)


def build_exe():
    src = os.path.join(BUILD, "pyi", "SafraConsole")
    if os.path.isdir(src):
        shutil.rmtree(src)
    run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
         "--windowed", "--name", "SafraConsole", "--icon", ICON,
         "--add-data", os.path.join(REPO, "ui") + ";ui",
         # bundle pywebview so the app renders in an embedded WebView2 window
         # (no dependency on the user's Edge/default browser); the hook pulls in
         # pythonnet + the WebView2 interop DLLs
         "--collect-all", "webview",
         "--distpath", os.path.join(BUILD, "pyi"),
         "--workpath", os.path.join(BUILD, "work"),
         "--specpath", BUILD,
         os.path.join(REPO, "safra_console.py")], cwd=REPO)
    exe = os.path.join(src, "SafraConsole.exe")
    if not os.path.isfile(exe):
        raise SystemExit("PyInstaller did not produce SafraConsole.exe")
    return src


def fetch_webview2_bootstrapper():
    """Download the Evergreen bootstrapper into build/ (cached across builds)."""
    if os.path.isfile(WV2_BOOTSTRAP) and os.path.getsize(WV2_BOOTSTRAP) > 100_000:
        return
    print("+ downloading WebView2 Evergreen bootstrapper")
    os.makedirs(BUILD, exist_ok=True)
    import urllib.request
    urllib.request.urlretrieve(WV2_BOOTSTRAP_URL, WV2_BOOTSTRAP)
    if os.path.getsize(WV2_BOOTSTRAP) < 100_000:
        raise SystemExit("WebView2 bootstrapper download looks wrong (too small)")


def build_installer(srcdir, iscc):
    os.makedirs(DIST, exist_ok=True)
    fetch_webview2_bootstrapper()
    iss = (ISS.replace("@VERSION@", VERSION).replace("@OUTDIR@", DIST)
              .replace("@ICON@", ICON).replace("@SRCDIR@", srcdir)
              .replace("@WV2SETUP@", WV2_BOOTSTRAP))
    iss_path = os.path.join(BUILD, "SafraConsole.iss")
    with open(iss_path, "w", encoding="utf-8") as f:
        f.write(iss)
    run([iscc, iss_path])
    setup = os.path.join(DIST, SETUP_NAME)
    if not os.path.isfile(setup):
        raise SystemExit("ISCC did not produce " + SETUP_NAME)
    return setup


def write_manifest(setup, base_url, notes):
    sha = hashlib.sha256()
    with open(setup, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            sha.update(chunk)
    manifest = {"version": VERSION,
                "url": base_url.rstrip("/") + "/" + SETUP_NAME,
                "sha256": sha.hexdigest(), "notes": notes}
    with open(os.path.join(DIST, "latest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    return sha.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL)
    ap.add_argument("--iscc", default=DEFAULT_ISCC)
    ap.add_argument("--notes", default="")
    args = ap.parse_args()
    if not os.path.isfile(args.iscc):
        raise SystemExit("Inno Setup compiler not found: {} (pass --iscc)".format(args.iscc))

    srcdir = build_exe()
    setup = build_installer(srcdir, args.iscc)
    sha = write_manifest(setup, args.base_url, args.notes)

    print("\nbuilt  ", setup, "({:.1f} MB)".format(os.path.getsize(setup) / 1e6))
    print("sha256 ", sha)
    print("feed   ", os.path.join(DIST, "latest.json"))
    print("publish: gh release create v{v} \"{s}\" \"{j}\"".format(
        v=VERSION, s=setup, j=os.path.join(DIST, "latest.json")))


if __name__ == "__main__":
    main()
